name: Test Export Docs

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: ./action.yml
        with:
          who-to-greet: 'Mona the Octocat'